# Use root/example as user/password credentials
version: "3.1"

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: testdb
        ports:
            - 27017:27017
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongo-volume:/data/db

volumes:
    mongo-volume:
