# Use root/example as user/password credentials
version: "3.1"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - 3306:3306
        networks:
            - mysql_network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        container_name: pma
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: user
            PMA_PASSWORD: pass
        ports:
            - 8080:80
        networks:
            - mysql_network

    phpmyadmin_admin:
        image: phpmyadmin
        restart: always
        container_name: pma_admin
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8081:80
        networks:
            - mysql_network

networks:
    mysql_network:
        name: mysql_network
